### ISSUE TITLE
bug: ibm_container_vpc_cluster resource's albs.id output doesn't work on Openshift clusters

### ISSUE THREAD

**Issue by jkerezsi** [terraform-ibm-modules/terraform-ibm-issue-tracker#1]
### Terraform CLI and Terraform IBM Provider Version

Terraform: `v0.13.5`
IBM provider: `1.25.0`

### Affected Resource(s)

* ibm_container_vpc_cluster

### Terraform Configuration Files

```hcl
resource "ibm_container_vpc_cluster" "vpc_cluster" {
  name              = var.vpc_cluster_name
  flavor            = var.machine_flavor
  worker_count      = var.default_worker_count
  vpc_id            = var.vpc_id
  resource_group_id = data.ibm_resource_group.resource_group.id
  kube_version      = var.kube_version
  entitlement       = var.openshift_entitlement
  cos_instance_crn  = ibm_resource_instance.openshift_cos.id

  # If making change here to this block, replicate in the worker pool block
  dynamic zones {
    for_each = var.subnet_ids
    content {
      subnet_id = zones.value
      name = "${var.region}-${index(var.subnet_ids, zones.value) + 1}"
    }
  }
}

output "out_vpc_cluster_alb_id" {
    value = ibm_container_vpc_cluster.vpc_cluster.albs[0].id
}
```
### Expected Behavior

I am using VPC gen 2 Openshift clusters. When I create a cluster an ALB will be automatically created with a name "kube-<clusterId>". In order to get the ID of the ALB i should be able get as an outpot of the cluster resource as per the documentation.

### Actual Behavior

When I try to access the ALB's ID from the cluster resource output I am getting an error saying that the "alb" object is empty.

### Steps to Reproduce

1. Create vpc 2 openshift cluster with Terraform by creating a vpc and vpc_cluster resource
2. Above step will trigger a creation of a load-balancer
3. Output the vpc_cluster resource's alb object, get LB's ID

**Comment by ocofaigh** [comment]
This is the wrong repo for provider issues. Provider issue belong in https://github.com/IBM-Cloud/terraform-provider-ibm/issues
