### ISSUE TITLE
apikey containers-kubernetes-key is not being destroyed

### ISSUE THREAD

**Issue by lionelmace** [terraform-ibm-modules/terraform-ibm-issue-tracker#12]
The module `vpc-kubernetes` create an apikey `containers-kubernetes-key`.
This key does not appear in any terraform template. yet this is being created when provisioning a cluster.

![image](https://user-images.githubusercontent.com/12241613/149348862-ae5c1205-2ff3-461f-9c1f-16ad81ee8c16.png)

This key is created internally when creating the cluster. The issue is that `terraform destroy` will not delete this key.

**Comment by ocofaigh** [comment]
Working as designed - closing (not related to terraform anyway)
