### ISSUE TITLE
Portworx scale up not working without some manual steps

### ISSUE THREAD

**Issue by sagarkrdev** [terraform-ibm-modules/terraform-ibm-issue-tracker#20]
**UseCase -** Add one/more new workers to an existing Portworx cluster and then run `terraform apply -auto-approve`, it should create block storage and attach block storage to new workers and this should result in Portworx successfully running on new workers as well.

**Observation -** After addition of new workers and running `terraform apply -auto-approve`, block storage is getting created and attached for new workers but Portworx is still running as a storage less node instead of storage node.

**Expectation -** The expectation is that after addition of new Portworx workers and running `terraform apply -auto-approve`, Portworx should be running on the newly added nodes as a storage node instead of storage less node if block storage has been attached.

**Resolution -** Portworx Service on the newly added node should be restarted after block storage provisioning and attachment to the node.

**How to reproduce -** 

- Install Portworx in a cluster with `terraform apply -auto-approve` 
- Add some more workers to the cluster
- Run `terraform apply -auto-approve` again
- Verify the Portworx status by exec(`oc exec -it -n kube-system $px-pod`) into one of the portworx daemon pod (`oc get po -n kube-system -l name=portworx`) and then run `/opt/pwx/bin/pxctl status`.
- It should show all the nodes where storage has been attached as storage node(`yes`).

**Comment by ocofaigh** [comment]
This module has been deprecated and is archived. Please use this link to use the terraform officially supported by the portworx team : https://registry.terraform.io/modules/portworx/portworx-enterprise/ibm/latest
