### ISSUE TITLE
Portworx destroy not working as expected

### ISSUE THREAD

**Issue by sagarkrdev** [terraform-ibm-modules/terraform-ibm-issue-tracker#21]
**UseCase -** Portworx destroy/uninstall/cleanup from a cluster where PX was installed using the same terraform script.

**Observation -** The cleanup or destroy step is not actually cleaning/uninstalling the Portworx resources/components from the cluster, it is just cleaning up the Portworx Service instance along with volume attachments and volumes.

**Expectation -** The expectation is that along with the Portworx service instance deletion and deletion of block storage created for Portworx, the cluster should not have Portworx components still running after destroy and basically the cluster should be ready for a new Portworx install.

**How to reproduce -** Install Portworx in a cluster with `terraform apply` and then destroy using `terraform destroy` and then again try to install Portworx on the same cluster using `terraform apply -auto-approve`. Portworx re-installation will fail since Portworx is still present in the cluster.

**Comment by ocofaigh** [comment]
This module has been deprecated and is archived. Please use this link to use the terraform officially supported by the portworx team : https://registry.terraform.io/modules/portworx/portworx-enterprise/ibm/latest
