### ISSUE TITLE
Objects for variables in module access-group

### ISSUE THREAD

**Issue by blacksd** [terraform-ibm-modules/terraform-ibm-issue-tracker#23]
In the variables for the `access-group` module, we define `dynamic_rules` as a `map(any)`: 

https://github.com/terraform-ibm-modules/terraform-ibm-iam/blob/68229dd99601d03e2d9134aaf95f55e54189d918/modules/access-group/variables.tf#L54-L57

But we use it implying a certain structure: 

https://github.com/terraform-ibm-modules/terraform-ibm-iam/blob/68229dd99601d03e2d9134aaf95f55e54189d918/modules/access-group/main.tf#L59-L63

A type `list(object)` (where `object` is a much stricter representation of the value we need) would be better suited for this variable.

**Comment by ocofaigh** [comment]
`terraform-ibm-iam` has been deprecated and archived. The access-group submodule has been moved to https://github.com/terraform-ibm-modules/terraform-ibm-iam-access-group

If you still have a requirement for this change, please create a new issue in https://github.com/terraform-ibm-modules/terraform-ibm-iam-access-group/issues

Thanks
