### ISSUE TITLE
Module is not compatible with latest provider version

### ISSUE THREAD

**Issue by l2fprod** [terraform-ibm-modules/terraform-ibm-issue-tracker#24]
`policies` have been removed from `ibm_kms_key`

“Blocks of type “policies” are not expected here”
from line 33 here: https://github.com/terraform-ibm-modules/terraform-ibm-kms/blob/main/modules/key-protect/main.tf

**Comment by ocofaigh** [comment]
:spider_web:`terraform-ibm-kms` is no longer maintained and is archived. Use one of the following supported modules to provison KMS resources: 
- [terraform-ibm-key-protect-all-inclusive](https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-all-inclusive)
- [terraform-ibm-key-protect](https://github.com/terraform-ibm-modules/terraform-ibm-key-protect)
- [terraform-ibm-kms-key](https://github.com/terraform-ibm-modules/terraform-ibm-kms-key)
- [terraform-ibm-kms-key-ring](https://github.com/terraform-ibm-modules/terraform-ibm-kms-key-ring)
