### ISSUE TITLE
Database: README cut/paste errors.

### ISSUE THREAD

**Issue by umarali-nagoor** [terraform-ibm-modules/terraform-ibm-issue-tracker#3]
**Describe the bug**
READMEs in some of the database module examples having cut/paste issue.

For example this one 
https://github.com/terraform-ibm-modules/terraform-ibm-database/tree/main/examples/simple-etcd
seems to have been copied from the elasticsearch one because it says: 
This example is used to provision simple databases for elasticsearch Database on IBM Cloud Infrastructure.

Please check even other READMEs.

**Comment by ocofaigh** [comment]
`terraform-ibm-database` has been deprecated and archived. See the current readme for alternatives -> https://github.com/terraform-ibm-modules/terraform-ibm-database/blob/master/README.md#module-archived
