### ISSUE TITLE
VPC Example does not reference attribute subnet_name_prefix

### ISSUE THREAD

**Issue by lionelmace** [terraform-ibm-modules/terraform-ibm-issue-tracker#31]
I noticed an issue in this doc [vpc module](https://github.com/terraform-ibm-modules/terraform-ibm-vpc/tree/master/modules/vpc)

The example reference the attribute `subnet_name`. Yet, the list of inputs only referencing `subnet_name_prefix`.

Which one is the correct one to use?

**Comment by ocofaigh** [comment]
`terraform-ibm-vpc` has been deprecated and archived. See the current readme for alternatives -> https://github.com/terraform-ibm-modules/terraform-ibm-vpc/blob/master/README.md#module-archived
