### ISSUE TITLE
GCAT Feedback: OUTPUTS -  Improving the outputs, they are very minimal

### ISSUE THREAD

**Issue by umarali-nagoor** [terraform-ibm-modules/terraform-ibm-issue-tracker#34]
GCAT feedback

Capture as many resource arguments as possible as module outputs

**Comment by ocofaigh** [comment]
`terraform-ibm-vpc` has been deprecated and archived. See the current readme for alternatives -> https://github.com/terraform-ibm-modules/terraform-ibm-vpc/blob/master/README.md#module-archived
