### ISSUE TITLE
GCAT Feedback:  Variables - Enhance the usage of variables and make them more user friendly

### ISSUE THREAD

**Issue by umarali-nagoor** [terraform-ibm-modules/terraform-ibm-issue-tracker#35]
GCAT feedback

* Improve the variables, and how it can be made consumable.
* Too many variables, makes it difficult to use
* Add validation checks to variable values

**Comment by ocofaigh** [comment]
`terraform-ibm-vpc` has been deprecated and archived. See the current readme for alternatives -> https://github.com/terraform-ibm-modules/terraform-ibm-vpc/blob/master/README.md#module-archived
