### ISSUE TITLE
Problem with boot_volumes and conditions

### ISSUE THREAD

**Issue by Rodi26** [terraform-ibm-modules/terraform-ibm-issue-tracker#36]
Every time I am trying to use this module, I get the following error : 

> `on .terraform/modules/instance/variables.tf line 149, in variable "boot_volume":
>     condition     = length(var.boot_volume) <= 1
> Invalid value for "value" parameter: argument must not be null.`

That is an optional parameter, I do not understand why that is an issue.

**Comment by ocofaigh** [comment]
`terraform-ibm-vpc-vsi` is no longer maintained and is archived. Use the following supported module to provision a VSI: [terraform-ibm-landing-zone-vsi](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi)
