### ISSUE TITLE
terraform-ibm-modules template forces run with invalid variables for module

### ISSUE THREAD

**Issue by jvallexm** [terraform-ibm-modules/terraform-ibm-issue-tracker#38]
Migrating code from https://github.com/Cloud-Schematics/key-management-module and trying to run the tests using the command

```shell
 make run-tests-local
```

results in my code being tested with unneeded variables
```shell
terraform [apply -input=false -auto-approve -var prefix=mod-template-nntil2 -var region=jp-osa -var resource_group= -var resource_tags=[] -lock=false]
```

These variables are not supported by my template configuration, and I can't find them doin a search. How can I remove these from the .go tests?

**Comment by vburckhardt** [comment]
Variables are coming from the go files template under the tests folder - there is some more details at https://terraform-ibm-modules.github.io/documentation/#/contribute-module?id=update-the-pr-tests

**Comment by jvallexm** [comment]
@vburckhardt Where in the test template? I'm looking at them and I do not see those. There are two `.go` files in the test folder and neither of them reference these two variables. any more information would be helpful

**Comment by jvallexm** [comment]
@vburckhardt any update on where they are and how to remove them?

**Comment by ocofaigh** [comment]
Have reached out directly to Jennifer to help here

**Comment by ocofaigh** [comment]
The link in https://terraform-ibm-modules.github.io/documentation/#/contribute-module?id=update-the-pr-tests is not the full docs. Here is correct URL https://terraform-ibm-modules.github.io/documentation/#/tests
