### ISSUE TITLE
Repo Request for ICSE Modules

### ISSUE THREAD

**Issue by jvallexm** [terraform-ibm-modules/terraform-ibm-issue-tracker#40]
- [ ] 1. terraform-ibm-icse-landing-zone
- [ ] 2. terraform-ibm-icse-baremetal-deployment
- [ ] 3. terraform-ibm-icse-f5-deployment
- [x] 4. terraform-ibm-icse-cloud-services
- [x] 5. terraform-ibm-icse-cos-module
- [ ] 6. terraform-ibm-icse-appid-module
- [x] 7. terraform-ibm-icse-vpe-module
- [ ] 8. terraform-ibm-icse-vsi-module
- [ ] 9. terraform-ibm-icse-vpn-gateway-module
- [x] 10. terraform-ibm-icse-subnet-module
- [ ] 11. terraform-ibm-icse-security-group-rules-module
- [x] 12. terraform-ibm-icse-security-group-module
- [x] 13. terraform-ibm-icse-public-gateway-module
- [x] 14. terraform-ibm-icse-network-acl-module
- [ ] 15. terraform-ibm-icse-vpc-network-module
- [ ] 16. terraform-ibm-icse-flow-logs-module
- [x] 17. terraform-ibm-icse-vpc-address-prefix-module
- [ ] 18. terraform-ibm-icse-atracker-module
- [ ] 19. terraform-ibm-icse-vsi-deployment-module
- [ ] 20. terraform-ibm-icse-cluster-module
- [ ] 21. terraform-ibm-icse-edge-vpc-network-module
- [ ] 22. terraform-ibm-icse-detailed-network-acl-rules-module
- [ ] 23. terraform-ibm-icse-custom-dns-module

**Comment by vburckhardt** [comment]
@jvallexm - Could we go by wave of groups of 2-3 repos here, so that we do not end up with 23 repos with template for a few weeks in the org?

**Comment by ocofaigh** [comment]
I can work with Jennifer to get these created. Will create in batches as per https://github.com/terraform-ibm-modules/terraform-ibm-issue-tracker/issues/40#issuecomment-1212930936

**Comment by ocofaigh** [comment]
I believe these are no longer required so going to close the issue. @jvallexm Feel free to re-open if needed
