### ISSUE TITLE
Publish to catalog the 'Standard' variation as part of the Secure Landing Zone publish

### ISSUE THREAD

**Issue by kbiegert** [terraform-ibm-modules/terraform-ibm-issue-tracker#44]
Once issue https://github.com/terraform-ibm-modules/terraform-ibm-issue-tracker/issues/43 has been merged, the Standard variation needs to be published to the catalog.   Variations are published individually.

**Comment by kbiegert** [comment]
A question possibly for this work is which catalog offering to publish to.  There are two offerings at the moment.  One has been approved and published through the IBM process and it has been the offering that new versions of the SLZ Power variation from the internal git repo have been publishing to.

The other offering is an offering that has been getting updates from the external git repo.  This offering should be deprecated as soon as publishing to the offering above is complete in my opinion.

**Comment by ocofaigh** [comment]
There is an internal issue for this, and a PR already exists for this: https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/81

I am going to close this issue so I don't have to track it in two different place. PR should be merged today anyway
