### ISSUE TITLE
terraform-ibm-landing-zone Basic Example Documentation

### ISSUE THREAD

**Issue by daniel-butler-irl** [terraform-ibm-modules/terraform-ibm-issue-tracker#47]
The basic example found https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/tree/main/examples/basic requires an SSH key. There should be documentation/link in the readme on how to generate this.

**Comment by ocofaigh** [comment]
Potentially covered by https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/175 ?

**Comment by SirSpidey** [comment]
There's nothing in the landing zone readme file that says how to generate the SSH. But do the updated variables address your issue, @daniel-butler-irl?

**Comment by vburckhardt** [comment]
This should be added on top of https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/175

Just link up to https://cloud.ibm.com/docs/vpc?topic=vpc-ssh-keys

**Comment by SirSpidey** [comment]
closed by PR 189
