### ISSUE TITLE
"diagram [which] illustrates the deployment architecture" is missing in docs

### ISSUE THREAD

**Issue by steven-collins-omega** [terraform-ibm-modules/terraform-ibm-issue-tracker#49]
See screenshot (macOS Monterey 12.6, Firefox 105.0.1)

![image](https://user-images.githubusercontent.com/1479479/192880878-944e6a18-b4ce-4ff3-b4fb-d4d2ecf347a3.png)

**Comment by SirSpidey** [comment]
@steven-collins-omega I see the image. If you are still not seeing it, are you seeing other images, such as the badges at top of the readme file?

here's what I see
<img width="542" alt="image" src="https://user-images.githubusercontent.com/8194208/193652132-dc3422ff-7a3e-40e3-a981-4ef034902993.png">

**Comment by SirSpidey** [comment]
Closing because of no response.
