### ISSUE TITLE
Global Resource Tags not available at IBM Provider

### ISSUE THREAD

**Issue by Manikandanmuru** [terraform-ibm-modules/terraform-ibm-issue-tracker#58]
### Description
We need to assign the "Resource Tags" to the resources created by Terraform. At this moment we only have the option to create resource tags for individual resources. It's exceedingly difficult to add the resource tags individually for 100s of resources we create.  We need to declare the "resource tags" globally such as at "IBM Provider". I could see AWS has such options.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/resource-tagging

### New or affected modules

IBM resource tag 

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by Manikandanmuru** [comment]
Please suggest me do we have any option to declare the IBM Resource Tag at the global level or Module instead of individual resources ??

**Comment by ocofaigh** [comment]
BTW, each of the modules we support has a explicit resource tag variable in which you can pass a list of resource tags too. For example: https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/blob/0162cb4dc9f8f5f0f274b38bca07a78aa0c99f58/variables.tf#L25

**Comment by ocofaigh** [comment]
Going to close this issue - if you need any support on any of the modules in this org, feel free to re-open
