### ISSUE TITLE
[New repo]: New Terraform module repo for deploying a zVSI

### ISSUE THREAD

**Issue by Roavill2** [terraform-ibm-modules/terraform-ibm-issue-tracker#59]
### New or existing repo?

Contributing new repo

### Suggested repo name

terraform-ibm-zVSI

### Short description of the module

This module will take the basic example of One VPC and One VSI and use it to create a z/OS VSI with the accompany networking being set up.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ocofaigh** [comment]
As per internal slack, I have created https://github.com/terraform-ibm-modules/terraform-ibm-zvsi
