### ISSUE TITLE
Provider not catching error in event streams module

### ISSUE THREAD

**Issue by Aayush-Abhyarthi** [terraform-ibm-modules/terraform-ibm-issue-tracker#63]
##

Provider is not throwing error in the event streams module (https://github.com/terraform-ibm-modules/terraform-ibm-event-streams) when kms encryption is enabled in standard plan.

**Comment by ocofaigh** [comment]
@Aayush-Abhyarthi Provider issues are created here -> https://github.com/IBM-Cloud/terraform-provider-ibm/issues
You will have to include alot more information to the provider. Don't reference our module, reference the IBM provider resource that has the issue (aka `ibm_resource_instance`)

**Comment by maheshwarishikha** [comment]
Provider issue created - https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4662
