### ISSUE TITLE
[New repo]: New Terraform module repo

### ISSUE THREAD

**Issue by losdevnull** [terraform-ibm-modules/terraform-ibm-issue-tracker#64]
### New or existing repo?

Contributing new repo

### Suggested repo name

terraform-ibm-vcf-on-vpc

### Short description of the module

Terraform templates to deploy VPC assets following VMware Cloud Foundation (VCF) architecture in IBM Cloud

### More information

We prefer this to be created as private repo.  For background of the reason of private repo, please refer to: 
https://ibm-cloudplatform.slack.com/archives/C02SDGCJAB1/p1688045619198279?thread_ts=1688032695.776949&cid=C02SDGCJAB1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ocofaigh** [comment]
Created private repo https://github.com/terraform-ibm-modules/terraform-ibm-vcf-on-vpc and set it up with `github-vmware-admins` and `github-vmware-mergers` teams
