### ISSUE TITLE
[New repo]: New Terraform module repo

### ISSUE THREAD

**Issue by namratabhadauriya** [terraform-ibm-modules/terraform-ibm-issue-tracker#66]
### New or existing repo?

Contributing new repo

### Suggested repo name

terraform-ibm-enterprise

### Short description of the module

Terraform module for creating enterprise hierarchy, which can have multiple child accounts, account groups created in a tree structure based on input passed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ocofaigh** [comment]
@namratabhadauriya I have created https://github.com/terraform-ibm-modules/terraform-ibm-enterprise
