### ISSUE TITLE
[Event notifications]: New Terraform module repo

### ISSUE THREAD

**Issue by VidyasagarMSC** [terraform-ibm-modules/terraform-ibm-issue-tracker#70]
### New or existing repo?

Migrating existing repo

### Suggested repo name

terraform-ibm-event notifications

### Short description of the module

Migrating event notifications Terraform module

### Maintaining team

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ocofaigh** [comment]
Created https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications

**Comment by ocofaigh** [comment]
@VidyasagarMSC I haven't seen any activity in https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications so I was just wondering if you still had plans to contribute code to this which supports creating an Event Notification instance?
