### ISSUE TITLE
Error in output for port and hostname

### ISSUE THREAD

**Issue by shipra101** [terraform-ibm-modules/terraform-ibm-issue-tracker#72]
### Affected modules

- [terraform-ibm-icd-redis](https://github.com/terraform-ibm-modules/terraform-ibm-icd-redis)
- [terraform-ibm-icd-postgresql](https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql)

### Terraform CLI and Terraform provider versions

* Terraform version:
* Provider version:

### Terraform output

` 2023/08/08 07:55:46 Terraform apply | Error: Error in function call
 2023/08/08 07:55:46 Terraform apply | 
 2023/08/08 07:55:46 Terraform apply |   on .terraform/modules/icd_redis/outputs.tf line 44, in output "hostname":
 2023/08/08 07:55:46 Terraform apply |   44:   value       = length(var.service_credential_names) > 0 ? nonsensitive(ibm_resource_key.service_credentials[keys(var.service_credential_names)[0]].credentials["connection.rediss.hosts.0.hostname"]) : length(var.users) > 0 ? nonsensitive(flatten(data.ibm_database_connection.database_connection[0].rediss[0].hosts[0].hostname)) : null
 2023/08/08 07:55:46 Terraform apply |     ├────────────────
 2023/08/08 07:55:46 Terraform apply |     │ while calling flatten(list)
 2023/08/08 07:55:46 Terraform apply |     │ data.ibm_database_connection.database_connection[0].rediss[0].hosts[0].hostname is "45bd37dc-9c75-46d9-99e7-a943bcfcd340.497129fd685f442ca4df759dd55ec01b.databases.appdomain.cloud"
 2023/08/08 07:55:46 Terraform apply | 
 2023/08/08 07:55:46 Terraform apply | Call to function "flatten" failed: can only flatten lists, sets and tuples.
 2023/08/08 07:55:46 Terraform apply | 
 2023/08/08 07:55:46 Terraform apply | Error: Error in function call
 2023/08/08 07:55:46 Terraform apply | 
 2023/08/08 07:55:46 Terraform apply |   on .terraform/modules/icd_redis/outputs.tf line 49, in output "port":
 2023/08/08 07:55:46 Terraform apply |   49:   value       = length(var.service_credential_names) > 0 ? nonsensitive(ibm_resource_key.service_credentials[keys(var.service_credential_names)[0]].credentials["connection.rediss.hosts.0.port"]) : length(var.users) > 0 ? nonsensitive(flatten(data.ibm_database_connection.database_connection[0].rediss[0].hosts[0].port)) : null
 2023/08/08 07:55:46 Terraform apply |     ├────────────────
 2023/08/08 07:55:46 Terraform apply |     │ while calling flatten(list)
 2023/08/08 07:55:46 Terraform apply |     │ data.ibm_database_connection.database_connection[0].rediss[0].hosts[0].port is 32276
 2023/08/08 07:55:46 Terraform apply | 
 2023/08/08 07:55:46 Terraform apply | Call to function "flatten" failed: can only flatten lists, sets and tuples.`

### Expected behavior
The terraform apply command to run successfully 

### Actual behavior
The [terraform provider documentation](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/database_connection#hosts) states that the hostname and port are strings .
Since strings can't be flattened, we are getting this error

### Steps to reproduce (including links and screen captures)

1. Run `terraform apply`

We have raised PR's for the fix of this issue : 
https://github.com/terraform-ibm-modules/terraform-ibm-icd-redis/pull/192
https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/pull/256

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
Thank you for reporting this! I have approved https://github.com/terraform-ibm-modules/terraform-ibm-icd-redis/pull/192 and https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql and will merge once pipeline passes. Going to keep the issue open as we may have other ICD modules that need the same fix. Someone from the core team will check and update.

**Comment by shipra101** [comment]
Thanks @ocofaigh, when can we expect to get this fix in the new release of these modules?

**Comment by ocofaigh** [comment]
@shipra101 The fix is already released. See https://github.com/terraform-ibm-modules/terraform-ibm-icd-redis/releases/tag/v1.0.1 and https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/releases/tag/v3.4.5

**Comment by ocofaigh** [comment]
@akocbek is rolling out the fix to all other ICD modules, as well as plugging the test gap
