### ISSUE TITLE
[New repo]: New Terraform module repo

### ISSUE THREAD

**Issue by jvallexm** [terraform-ibm-modules/terraform-ibm-issue-tracker#75]
### New or existing repo?

Migrating existing repo

### Suggested repo name

terraform-ibm-platinum-key-management

### Short description of the module

key management module for key protect / hpcs

### Maintaining team

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ocofaigh** [comment]
Hi @jvallexm 
Can you give more info on this modules please? How does it differ from any of these?

- https://github.com/terraform-ibm-modules/terraform-ibm-hpcs
- https://github.com/terraform-ibm-modules/terraform-ibm-key-protect
- https://github.com/terraform-ibm-modules/terraform-ibm-kms-key
- https://github.com/terraform-ibm-modules/terraform-ibm-kms-key-ring
- https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-all-inclusive

**Comment by jvallexm** [comment]
@ocofaigh it can use both kms or hpcs, it has easy to understand readable modules, and is interoperable with msp modules. this is different. please create, thanks.

**Comment by vburckhardt** [comment]
Hi @jvallexm - if possible, we'd like to avoid duplication of modules in the same area. https://github.com/terraform-ibm-modules/terraform-ibm-kms-key https://github.com/terraform-ibm-modules/terraform-ibm-kms-key-ring already works with both kms and hpcs ( and have regression testing against them). I think we should attempt to merge the msp ecosystem into the TIM one if possible rather than building 2 different ecosystem of similar modules working well together but not with others. Could you identify the interoperability change that may be done in the modules that Conall mentioned?

**Comment by jvallexm** [comment]
@vburckhardt i would make significant changes to readability and the way that resources are created and provisioned that would cause breaking changes in regression testing, so updating existing modules is not an option unless you would be fine with breaking regression changes. i understand wanting to keep modules the same, however in this case the modules have different and distinct usecases, so i would recommend a new module

**Comment by jvallexm** [comment]
@vburckhardt in addition, the module i'm requesting handles both keys and authorization policies for either kms or hpcs, neither of which are covered by these modules. i would be happy to look into using the other child modules as part of the code, however this new codebase will require the creation of a separate module unless breaking changes can be made to regression testing

**Comment by ocofaigh** [comment]
@jvallexm How about going ahead and creating a PR in the current repos, even if they are breaking changes, and we can then review them. Similar to the way you did with https://github.com/terraform-ibm-modules/terraform-ibm-security-group/pull/131 (which should be merged today btw)

**Comment by ocofaigh** [comment]
Going to try and re-use existing modules instead of creating duplicate one - closing
