### ISSUE TITLE
[New repo for provisioning AT instance in an account]: New Terraform module repo

### ISSUE THREAD

**Issue by ssghosh1990** [terraform-ibm-modules/terraform-ibm-issue-tracker#76]
### New or existing repo?

Contributing new repo

### Suggested repo name

terraform-ibm-activity-tracker

### Short description of the module

This module should provision an Activity Tracker instance in a region.

### Maintaining team

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ocofaigh** [comment]
@ssghosh1990 FYI, AT provisioning is supported in https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/
