### ISSUE TITLE
[terraform-ibm-powervs-vmrm]: New Terraform module repo

### ISSUE THREAD

**Issue by Jeskiran** [terraform-ibm-modules/terraform-ibm-issue-tracker#77]
### New or existing repo?

Contributing new repo

### Suggested repo name

terraform-ibm-powervs-vmrm

### Short description of the module

VM Recovery Manager is a product, which handles simplified DR for PowerVS. As part of this module, DR orchestrator would be installed and configured. User can decide the Orchestrator VM configuration and accordingly orchestrator would be installed, configured for the configuration that user provided.

### Maintaining team

Projects

### Request team name

vmrm

### New team admin users

JesKiran
jechitti@in.ibm.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ocofaigh** [comment]
@Jeskiran 
I have created https://github.com/terraform-ibm-modules/terraform-ibm-powervs-vmrm and its hooked up with the new teams [github-power-admins](https://github.com/orgs/terraform-ibm-modules/teams/github-power-admins) and [github-power-mergers](https://github.com/orgs/terraform-ibm-modules/teams/github-power-mergers). I added you to both of the teams.
