### ISSUE TITLE
[terraform-ibm-powervs-powerha]: New Terraform module repo

### ISSUE THREAD

**Issue by Jeskiran** [terraform-ibm-modules/terraform-ibm-issue-tracker#78]
### New or existing repo?

Contributing new repo

### Suggested repo name

terraform-ibm-powervs-powerha

### Short description of the module

PowerHA provides high availability for the resources. As part of this module, targeted to deploy VMs and install, configure PowerHA on the deployed VMs.

### Maintaining team

Projects

### Request team name

powerha

### New team admin users

JesKiran

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ocofaigh** [comment]
@Jeskiran 
I have created https://github.com/terraform-ibm-modules/terraform-ibm-powervs-powerha and its hooked up with the new teams [github-power-admins](https://github.com/orgs/terraform-ibm-modules/teams/github-power-admins) and [github-power-mergers](https://github.com/orgs/terraform-ibm-modules/teams/github-power-mergers). I added you to both of the teams.
