### ISSUE TITLE
[New repo]: New Terraform module repo

### ISSUE THREAD

**Issue by surajsbharadwaj** [terraform-ibm-modules/terraform-ibm-issue-tracker#80]
### New or existing repo?

Migrating existing repo

### Suggested repo name

terraform-ibm-powervs-workspace

### Short description of the module

Sets up and configures a Power Virtual Servers workspace with ssh key, private and public subnets, cloud connections and connects it to existing transit gateway

### Maintaining team

Power

### More information

Please add suraj.bharadwaj@ibm.com to the merger and admin user of Power team

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ocofaigh** [comment]
@surajsbharadwaj Repo created https://github.com/terraform-ibm-modules/terraform-ibm-powervs-workspace
