### ISSUE TITLE
[terraform-ibm-base-security-services-da]: New Terraform module repo

### ISSUE THREAD

**Issue by bhakta-ibm** [terraform-ibm-modules/terraform-ibm-issue-tracker#81]
### New or existing repo?

Contributing new repo

### Suggested repo name

terraform-ibm-base-security-services-da

### Short description of the module

This module will provide a provisioning and configuring base security services (namely IBM Key Protect, Secret Manager and Security and Compliance Center). 

### Maintaining team

I need a new team

### Request team name

Cloud Security Services Team

### New team admin users

@bhakta-ibm (Dharmesh Bhakta)

### New team merger users

@bhakta-ibm (Dharmesh Bhakta)

### More information

This module will be the base for Security by default effort from IBM Cloud. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ocofaigh** [comment]
@bhakta-ibm I have done the following:

- Created 2 new teams and add you to both (you need to accept invite to the org first): `github-security-services-mergers` and `github-security-services-admin`
- Created new repo and set it up with the new team: https://github.com/terraform-ibm-modules/terraform-ibm-base-security-services-da

Please reach out if you need anything else
