### ISSUE TITLE
[terraform-ibm-core-security-services-da]: New Terraform module repo

### ISSUE THREAD

**Issue by bhakta-ibm** [terraform-ibm-modules/terraform-ibm-issue-tracker#85]
### New or existing repo?

Contributing new repo

### Suggested repo name

terraform-ibm-core-security-services-da

### Short description of the module

This module will provide a provisioning and configuring base security services (namely IBM Key Protect, Secret Manager and Security and Compliance Center).

### Maintaining team

Security Services

### New team admin users

Timothy.Yao@ibm.com
bhakta@ibm.com

### New team merger users

Timothy.Yao@ibm.com
bhakta@ibm.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ocofaigh** [comment]
stack repos will use the prefix stack-ibm- I’ll create the repo now based off our new stack template https://github.com/terraform-ibm-modules/stack-ibm-template

**Comment by ocofaigh** [comment]
Created https://github.com/terraform-ibm-modules/stack-ibm-core-security-services
