### ISSUE TITLE
[New repo]: New Terraform module repo for Web app Multi-Zone Resiliency Deployable Architecture

### ISSUE THREAD

**Issue by argeiger** [terraform-ibm-modules/terraform-ibm-issue-tracker#87]
### New or existing repo?

Contributing new repo

### Suggested repo name

terraform-ibm-web-app-mzr-da

### Short description of the module

The web app multi-zone resiliency pattern provides a solution design for a 3-tier web architecture deployment that meets high availability requirements for enterprise workloads. It uses cloud platform capabilities to deploy resilient applications on Virtual Servers for VPC.

### Maintaining team

New team

### Request team name

CCS (IBM Cloud Complex Solutions)

### New team admin users

Adam Geiger (argeiger)

### New team merger users

Adam Geiger (argeiger)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ocofaigh** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-web-app-mzr-da/pull/1
https://github.com/terraform-ibm-modules/repo-settings/pull/39
