### ISSUE TITLE
[New repo]: New Terraform DevSecOps stack repo

### ISSUE THREAD

**Issue by padraic-edwards** [terraform-ibm-modules/terraform-ibm-issue-tracker#89]
### New or existing repo?

Contributing new repo

### Suggested repo name

stack-ibm-devescops-alm

### Short description of the module

This stack will combine the DevSecOps infrastructure module with the DevSecOps ALM

### Maintaining team

DevSecOps

### New team admin users

padraic-edwards

### New team merger users

huayuenh

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vburckhardt** [comment]
Created https://github.com/terraform-ibm-modules/stack-ibm-devescops-alm
