### ISSUE TITLE
[New repo]: New Terraform module repo

### ISSUE THREAD

**Issue by ChuckCox** [terraform-ibm-modules/terraform-ibm-issue-tracker#91]
### New or existing repo?

Contributing new repo

### Suggested repo name

terraform-ibm-liberty-aas

### Short description of the module

Provisions and configures a Liberty as a Service instance into an IBM Cloud account. 

### Maintaining team

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ocofaigh** [comment]
@ChuckCox Here you go: https://github.com/terraform-ibm-modules/terraform-ibm-liberty-aas
