### ISSUE TITLE
[New repo]: New Terraform module repo

### ISSUE THREAD

**Issue by gayathribheemesh** [terraform-ibm-modules/terraform-ibm-issue-tracker#93]
### New or existing repo?

New repo

### Suggested repo name

terraform-ibm-powervs-cps

### Short description of the module

This repository will contains deployable architecture solutions that help in deploying Power Virtual Server for CPS. The solutions would be available in the IBM Cloud Catalog.

### Maintaining team

sshivaswamy@in.ibm.com
gayathrib@in.ibm.com
madhusudhan.kn@in.ibm.com

### New team admin users

sshivaswamy@in.ibm.com
gayathrib@in.ibm.com
madhusudhan.kn@in.ibm.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ocofaigh** [comment]
@gayathribheemesh Should the new team admins be added to the existing `github-projects-admins` team? Currently there is 1 admin in this group already, @seansund - Is it the same team?

**Comment by ocofaigh** [comment]
@gayathribheemesh Maybe you meant the Power team ([github-power-admins](https://github.com/orgs/terraform-ibm-modules/teams/github-power-admins)) ? The admins in this team are currently @Jeskiran and @surajsbharadwaj

**Comment by gayathribheemesh** [comment]
@ocofaigh I need to create a new repo and fork an existing one there.

**Comment by ocofaigh** [comment]
@gayathribheemesh yea I can create the repo, but I need to know who the admin and mergers should be. You mention in the issue that the maintaining team is `Projects` - but is that correct?

**Comment by gayathribheemesh** [comment]
[sshivaswamy@in.ibm.com]
[gayathrib@in.ibm.com]
[madhusudhan.kn@in.ibm.com]

These three people would be the admins and mergers list I do not have yet - Can we add the same members for now?

**Comment by ocofaigh** [comment]
@gayathribheemesh I need their github.com usernames please.
Also can you confirm who the owing team is? Is it Projects? It seems you may be from the Power team, so hence why I'm looking for clarification

**Comment by madhusudhan-kn** [comment]
Hi @ocofaigh  , The owing team for this is from IBM Cloud Pak System Team under IBM Automation. IBM Cloud Pak System already has an appliance offering, we are further looking to get our CPS software tested on IBM Cloud as DA for Power workloads.

**Comment by surajsbharadwaj** [comment]
@ocofaigh Please create a new group called CPS and assign @gayathribheemesh as admin :)

**Comment by surajsbharadwaj** [comment]
terraform-ibm-powervs-cps---> rename it to terraform-ibm-cps

**Comment by ocofaigh** [comment]
Repo is created: https://github.com/terraform-ibm-modules/terraform-ibm-cps

New teams have been created to manage this repo:
[github-cps-admins](https://github.com/orgs/terraform-ibm-modules/teams/github-cps-admins)
[github-cps-mergers](https://github.com/orgs/terraform-ibm-modules/teams/github-cps-mergers)

@gayathribheemesh I have added you to both of those team. Let me know who else should be added. You will need to accept an invite to the github org first

**Comment by gayathribheemesh** [comment]
Thanks so much @ocofaigh !
